global:
  scrape_interval:     1s
  scrape_timeout:      100ms

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'node-exporter'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'node-exporter:9100'
  - job_name: 'stromzaehler'
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'libsml-prometheus-exporter:8080'
